import 'dart:io';
import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../models/candidate.dart';
import '../../services/candidate_service.dart';

class PdfExportService {
  static const _primaryColor = PdfColor.fromInt(0xFF1E3A5F);
  static const _accentColor = PdfColor.fromInt(0xFF3B82F6);
  static const _greyColor = PdfColor.fromInt(0xFF64748B);
  static const _lightGrey = PdfColor.fromInt(0xFFF1F5F9);

  static Future<Uint8List> generate({
    required String schoolName,
    required String academicYear,
    required String? logoPath,
    required List<CandidateModel> candidates,
    required List<String> positions,
    required Map<String, CandidateModel> winners,
  }) async {
    final doc = pw.Document();
    final dateFormat = DateFormat('MMMM dd, yyyy');
    final generatedDate = dateFormat.format(DateTime.now());

    pw.MemoryImage? logo;
    if (logoPath != null && logoPath.isNotEmpty) {
      final file = File(logoPath);
      if (file.existsSync()) {
        logo = pw.MemoryImage(await file.readAsBytes());
      }
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(56),
        header: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Text(
            'School Election Management System',
            style: pw.TextStyle(
              fontSize: 8,
              color: _greyColor,
            ),
          ),
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 8),
          child: pw.Text(
            'Generated by School Election Management System',
            style: pw.TextStyle(
              fontSize: 8,
              color: _greyColor,
            ),
          ),
        ),
        build: (context) => [
          _buildHeader(schoolName, academicYear, logo, generatedDate),
          pw.SizedBox(height: 20),
          _buildSummarySection(candidates, positions, generatedDate),
          pw.SizedBox(height: 24),
          if (winners.isNotEmpty) ...[
            _buildWinnersSection(winners),
            pw.SizedBox(height: 24),
          ],
          _buildCandidatesSection(candidates),
          pw.SizedBox(height: 32),
          _buildSignatureSection(),
        ],
      ),
    );

    return await doc.save();
  }

  static pw.Widget _buildHeader(
    String schoolName,
    String academicYear,
    pw.MemoryImage? logo,
    String generatedDate,
  ) {
    return pw.Column(
      children: [
        if (logo != null)
          pw.Container(
            width: 72,
            height: 72,
            child: pw.Image(logo),
          ),
        if (logo != null) pw.SizedBox(height: 8),
        pw.Text(
          schoolName,
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: _primaryColor,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          academicYear,
          style: pw.TextStyle(
            fontSize: 12,
            color: _greyColor,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'Election Date: $generatedDate',
          style: pw.TextStyle(
            fontSize: 10,
            color: _greyColor,
          ),
        ),
        pw.Divider(thickness: 1.5, color: _accentColor),
      ],
    );
  }

  static pw.Widget _buildSummarySection(
    List<CandidateModel> candidates,
    List<String> positions,
    String generatedDate,
  ) {
    final totalVotes = candidates.fold(0, (sum, c) => sum + c.votes);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Election Summary'),
        pw.SizedBox(height: 10),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: pw.BoxDecoration(
            color: _lightGrey,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
            children: [
              _statItem('Candidates', candidates.length.toString()),
              _statItem('Total Votes', totalVotes.toString()),
              _statItem('Positions', positions.length.toString()),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _statItem(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: _primaryColor,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          label,
          style: pw.TextStyle(fontSize: 10, color: _greyColor),
        ),
      ],
    );
  }

  static pw.Widget _buildWinnersSection(Map<String, CandidateModel> winners) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Position-wise Winners'),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFE2E8F0), width: 0.5),
          columnWidths: {
            0: const pw.FixedColumnWidth(120),
            1: const pw.FixedColumnWidth(140),
            2: const pw.FixedColumnWidth(60),
            3: const pw.FixedColumnWidth(60),
            4: const pw.FixedColumnWidth(60),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: _primaryColor),
              children: ['Position', 'Winner Name', 'Class', 'Section', 'Votes']
                  .map((h) => _tableHeader(h))
                  .toList(),
            ),
            ...winners.entries.map((entry) {
              final c = entry.value;
              return pw.TableRow(
                children: [
                  _tableCell(entry.key),
                  _tableCell(c.name, bold: true),
                  _tableCell(c.className),
                  _tableCell(c.section),
                  _tableCell(c.votes.toString()),
                ],
              );
            }),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildCandidatesSection(List<CandidateModel> candidates) {
    final sorted = List<CandidateModel>.from(candidates);
    sorted.sort((a, b) {
      final positions = CandidateService.positions;
      final aIdx = positions.indexOf(a.position);
      final bIdx = positions.indexOf(b.position);
      if (aIdx != bIdx) return aIdx.compareTo(bIdx);
      return b.votes.compareTo(a.votes);
    });

    final maxVotes = sorted.isEmpty ? 1 : sorted.map((c) => c.votes).reduce((a, b) => a > b ? a : b);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('All Candidate Results'),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFE2E8F0), width: 0.5),
          columnWidths: {
            0: const pw.FixedColumnWidth(28),
            1: const pw.FixedColumnWidth(120),
            2: const pw.FixedColumnWidth(60),
            3: const pw.FixedColumnWidth(100),
            4: const pw.FixedColumnWidth(50),
            5: const pw.FixedColumnWidth(50),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: _primaryColor),
              children: ['#', 'Candidate Name', 'Roll No.', 'Position', 'Votes', 'Bar']
                  .map((h) => _tableHeader(h))
                  .toList(),
            ),
            ...sorted.asMap().entries.map((entry) {
              final i = entry.key;
              final c = entry.value;
              final ratio = maxVotes > 0 ? c.votes / maxVotes : 0.0;
              return pw.TableRow(
                children: [
                  _tableCell('${i + 1}'),
                  _tableCell(c.name, bold: true),
                  _tableCell(c.rollNumber),
                  _tableCell(c.position),
                  _tableCell(c.votes.toString()),
                  pw.Container(
                    height: 14,
                    child: pw.Stack(
                      children: [
                        pw.Container(
                          width: double.infinity,
                          height: 14,
                          decoration: pw.BoxDecoration(
                            color: _lightGrey,
                            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(7)),
                          ),
                        ),
                        pw.Container(
                          width: (ratio * 50),
                          height: 14,
                          decoration: pw.BoxDecoration(
                            color: _accentColor,
                            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(7)),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              );
            }),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildSignatureSection() {
    return pw.Column(
      children: [
        pw.Divider(thickness: 0.5, color: _greyColor),
        pw.SizedBox(height: 8),
        pw.Text(
          'Generated on: ${DateFormat('MMMM dd, yyyy – HH:mm').format(DateTime.now())}',
          style: pw.TextStyle(fontSize: 9, color: _greyColor),
        ),
        pw.SizedBox(height: 24),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 180,
                  height: 1,
                  color: _primaryColor,
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Principal Signature',
                  style: pw.TextStyle(fontSize: 10, color: _greyColor),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 180,
                  height: 1,
                  color: _primaryColor,
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Election Officer Signature',
                  style: pw.TextStyle(fontSize: 10, color: _greyColor),
                ),
              ],
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(left: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border(
          left: pw.BorderSide(color: _accentColor, width: 3),
        ),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: _primaryColor,
        ),
      ),
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  static pw.Widget _tableCell(String text, {bool bold = false}) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }
}